(define (simpsons-rule-integral f a b n)
    (define h (/ (- b a) (* 3 n)))
    (define (add-h x)
        (+ x h))
    (define (coef-f x)
        (cond ((even? (/ x h)) (* 2 (f x)))
            (else (* 4 (f x)))))
    (/ (* (sum coef-f 0 add-h b) h) 3))
(define (even? x)
    (= (remainder x 2) 0))
(define (sum term a next b) 
    (if (> a b)
        0
        (+ (term a) 
            (sum term (next a) next b))))
